# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8fd0678f2b6c98e6358d6a10dc11591846c2618bfc5e5057a94632f477b4b93657c4b59306641b95eafb70b677554f209f3f51c927d60f652cb14b2c2755392

test:
  secret_key_base: dfe68667b4c5737aa85e8ee89ef98f9e1107db7e9c40e9e3b2d1300390262d1be5d4a3afbc6986db272ae69b5158c5bd09adb424aa1407ce3af500ca2d087206

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
